# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EJWhatShouldIWear' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJWhatShouldIWear
   pod 'Alamofire', '~> 4.7.3'
   pod 'SideMenu', '~> 5.0.3'
   pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

  target 'EJWhatShouldIWearUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
