# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EJWhatShouldIWear' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJWhatShouldIWear
   pod 'Firebase/Analytics'
   pod 'Firebase/RemoteConfig'
   pod 'Firebase/InAppMessaging'
   pod 'Firebase/Database'
   pod 'Firebase/Crashlytics'
   
   pod 'Alamofire', '~> 4.7.3'
   pod 'SideMenu', '~> 5.0.3'
   pod 'Google-Mobile-Ads-SDK'
   pod 'SwiftyJSON', '~> 5.0.0'
   pod 'ESPullToRefresh', '~> 2.9'
   pod 'Protobuf', :inhibit_warnings => true

   target 'EJWhatShouldIWearTests' do
    inherit! :search_paths
 
   end

  target 'EJWhatShouldIWearUITests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
