# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EJWhatShouldIWear' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJWhatShouldIWear
   pod 'Firebase/Crashlytics'
   pod 'Firebase/Analytics'
   pod 'Firebase/Messaging'
   pod 'Firebase/RemoteConfig'
   pod 'Firebase/Database'
   pod 'Firebase/CoreOnly'
   pod 'Firebase/Firestore'
   # Optionally, include the Swift extensions if you're using Swift.
   pod 'FirebaseFirestoreSwift'
   pod 'Firebase/Storage'
   pod 'FirebaseInAppMessaging'

   pod 'Alamofire', '~> 5.4.0'
   pod 'SideMenu', '~> 5.0.3'
   pod 'Google-Mobile-Ads-SDK'
   pod 'SwiftyJSON', '~> 5.0.0'
   pod 'ESPullToRefresh', '~> 2.9'
   pod 'Protobuf', :inhibit_warnings => true
   pod 'SkeletonView'
   pod 'Moya', '~> 15.0.0-alpha.1'
   pod 'SDWebImage', '~> 5.10.0'

   target 'EJWhatShouldIWearTests' do
    inherit! :search_paths
 
   end

  target 'EJWhatShouldIWearUITests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
